### ISSUE TITLE
Script de creación de tablas tiene algunos fallos 

### ISSUE THREAD

**Issue by ecabrerar** [joedayz/titanic-javaee7#1]
ERROR 1100 (HY000) at line 124: Table 'pvm_cliente' was not locked with LOCK TABLES

**Comment by ecabrerar** [comment]
[fix_script_db.txt](https://github.com/joedayz/titanic-javaee7/files/81724/fix_script_db.txt)
Patch que corrige los errores en el archivo de creación de tablas.

**Comment by ecabrerar** [comment]
Archivo completo modificado

**Comment by joedayz** [comment]
@ecabrerar  gracias por la corrección. También les cuento que se puede autogenerar las tablas a partir  de las entidades Java. El tip es ir al persistence.xml, comentar la linea <non-jta-data-source/> y descomentar <properties> y como el <property name="hibernate.hbm2ddl.auto" value="update" /> tiene valor "update" generará las tablas.  Eso si tienen que ejecutarlo y tras un intento de login generará las tablas en la BD.

<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd"
             version="2.1">

<persistence-unit name="PedidoPU">
    <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>

```
<!--non-jta-data-source>java:comp/env/jdbc/titanic</non-jta-data-source-->
<properties>

    <property name="javax.persistence.jdbc.url" value="jdbc:mysql://localhost/titanic_diplomado" />
    <property name="javax.persistence.jdbc.user" value="root" />
    <property name="javax.persistence.jdbc.password" value="12345678" />
    <property name="javax.persistence.jdbc.driver" value="com.mysql.jdbc.Driver" />

    <property name="hibernate.hbm2ddl.auto" value="update" />
    <property name="hibernate.show_sql" value="false" />
    <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect" />

</properties>
```

</persistence-unit>

</persistence>
